entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  consulCatalog:
    endpoint:
      address: "consul:8500"
    exposedByDefault: false
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: DEBUG
