http:
  routers:
    deviceservice-router:
      rule: "PathPrefix(`/devices`)"
      service: deviceservice-service
      entryPoints:
        - web
      middlewares:
        - strip-prefix

  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes:
          - /devices

  services:
    deviceservice-service:
      loadBalancer:
        servers:
          - url: "http://deviceservice:4000"
